version: '3.8'
name: 'fitness-workouts'
services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - "127.0.0.1:5173:5173"

  trainings-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/trainings
    ports:
      - "127.0.0.1:3001:$PORT"
    env_file:
      - .env
